### ISSUE TITLE
Cursor jumps on delete on auto-validating field

### ISSUE THREAD

**Issue by zkoch** [PolymerElements/gold-cc-input#20]
To reproduce:

1.) Type in 4111 1111 1111 1111 on auto-validating input field
2.) Place cursor behind "4" and backspace to remove the 4
3.) Notice that cursor jumps to the end of the input instead of staying at the front

**Comment by notwaldorf** [comment]
Thanks for finding this!

**Comment by notwaldorf** [comment]
Fixed by https://github.com/PolymerElements/gold-cc-input/pull/21
