### ISSUE TITLE
Polymer 2.0-preview 

### ISSUE THREAD

**Issue by bmodeprogrammer** [PolymerElements/gold-cc-input#59]
### Description
Will have Polymer 2.0 compatibility for this component?

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by Oupsla** [comment]
Any news about this compatibility ?

**Comment by H3dz** [comment]
@Oupsla I forked the component and updated it for 2.0, you can use the following commits to include them in your project:

    "gold-cc-cvc-input": "H3dz/gold-cc-cvc-input#13045459f62c421a0c172c3baa6b07c2a8645607",
    "gold-cc-input": "H3dz/gold-cc-input#751f0805a53d8f966e69587f2b318fa9055c7f95",
    "gold-cc-expiration-input": "H3dz/gold-cc-expiration-input#cd246dcc32164b92d3edee2831c71117e4bb49e9"
